### ISSUE TITLE
Global mouse hook

### ISSUE THREAD

**Issue by jacek-lapinski** [shintadono/Win32#1]
Is your library can be used to create global mouse hook? If so, can you provide me some snippet code?

**Comment by shintadono** [comment]
Hi, actually I don't know, if that would be possible with the available bindings - never needed something like that.
This repo is only containing C# bindings for parts of the Windows API, so if you know how to do it with that API (there are probably examples of StackOverflow & Co. for Windows API based hooks), you can try rebuild it using this repo's classes.
